# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven


on:
 push:
  branches: 
   - main
   - master


 pull_request:
  branches: [ master ]
 schedule:
    # * is a special character in YAML so you have to quote that triggers the workflow every day at 5:30
    - cron:  '30 5 * * *'



jobs:
 build:
  runs-on: windows-latest

  #   steps:
  steps:
    - name: step 1 - check out the main branch from GitHub
      uses: actions/checkout@v2


    - name: step 2 - Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name:  Install Google Chrome # Using shell script to install Google Chrome
      run:   |
       chmod +x ./scriptInstal/chromScript.sh
                   ./scriptInstal/chromScript.sh
    - name: Build with Maven
      run: mvn -B package --file pom.xml


#   - name: Build with Maven
